Metrics/LineLength:
  Max: 120

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 31.11

Metrics/MethodLength:
  Max: 30

Style/FlipFlop:
  Exclude:
    - 'nero-abuse-report.rb'
